# Generated by Django 5.0.2 on 2024-03-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllCustomerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.IntegerField()),
                ('cust_name', models.CharField(max_length=100)),
                ('cust_address', models.TextField()),
                ('cust_number', models.IntegerField()),
                ('cust_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('user_address', models.TextField()),
                ('user_number', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('req_date', models.DateField()),
                ('req_title', models.CharField(max_length=100)),
                ('req_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WebCustomersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('user_address', models.TextField()),
                ('user_number', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_pass', models.CharField(max_length=100)),
            ],
        ),
    ]
